apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 8080        # <--- ÄNDRAT till 8080
      targetPort: 8080  # <--- ÄNDRAT till 8080
  selector:
    app: wordpress
    tier: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: bitnami/wordpress:latest  # <--- change to bitnami image
        name: wordpress
        ports:
        - containerPort: 8080            # <--- ÄNDRAT till 8080
          name: wordpress
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"              # Ökade lite för säkerhets skull
            cpu: "500m"
        env:
        - name: WORDPRESS_DATABASE_HOST    # <--- OBS: Nytt namn på variabeln
          value: "wordpress-mysql"
        - name: WORDPRESS_DATABASE_PORT_NUMBER # <--- Vi måste ange porten
          value: "3306"
        - name: WORDPRESS_DATABASE_USER    # <--- OBS: Nytt namn
          value: "wp_user"
        - name: WORDPRESS_DATABASE_PASSWORD # <--- OBS: Nytt namn
          value: "wp_pass"
        - name: WORDPRESS_DATABASE_NAME    # <--- OBS: Nytt namn
          value: "wordpress"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /bitnami/wordpress   # <--- OBS: Bitnami sparar filer här
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc